[project]
name = 'ordinacks'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[contracts.ordinacks]
path = 'contracts/ordinacks.clar'
clarity_version = 1
epoch = 2.0

[contracts.ordinacks-mint]
path = 'contracts/ordinacks-mint.clar'
clarity_version = 1
epoch = 2.0

[contracts.utils]
path = 'contracts/utils.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
